const express = require('express');
const hbs = require('express-handlebars');
const nodemailer = require('nodemailer');
const path = require('path');
require('dotenv').config();
const port = process.env.PORT;

const app = express();

// Middlewares
app.use(express.json());

// View engine setup
app.engine('hbs', hbs({ extname: '.hbs' }));
app.set('view engine', '.hbs');

// Set static folder
app.use('/public', express.static(path.join(__dirname, 'public')));

// Routes
app.get('/', (req, res) => {
  res.render('contact-form', { layout: false });
});

app.post('/send', async (req, res) => {
  const output = `
      <div>
      <h3>Message successfully sent!</h3>
        <p>This message was generated by Node Email Service</p>
        <p>2019 &copy; Svetoslav<p>
      </div>
  `;

  const transporter = nodemailer.createTransport({
    port: 587,
    secure: false, // upgrade later with STARTTLS
    service: 'gmail',
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.USER_EMAIL, // generated ethereal user
      pass: process.env.PASSWORD // generated ethereal password
    }
  });

  const mailOptions = {
    from: `${process.env.USER_EMAIL}`, // sender address
    // TESTING PURPOSE ONLY
    to: `example1@yahoo.com, example2@yahoo.com`, // list of receivers
    subject: 'Email Nodemailer', // Subject line
    text: 'Hello from Nodemailer', // plain text body
    html: output // html body
  };

  // send mail with defined transport object
  const mail = await transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }

    res.send(output);

    console.log('Message sent: %s', info.messageId);
    // Preview only available when sending through an Ethereal account
    console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
  });
});

app.listen(
  port,
  console.log(` =====> ✔ Server running at http://localhost:${port}`)
);
